### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by grache** [PitchInteractiveInc/Phinch#53]
Hi everyone, 
I am trying to install phinch on my mac. When I try to compile Phinch code with

coffee -o scripts/ -cw src/ 

it stalls when doing this step
11:10:05 - compiled /Users/me/Phinch-master/src/zipWorker.coffee

I tried several time but with the same result. Can anyone help me?
Thanks
Gra

**Comment by shiltemann** [comment]
Hi, it doesn't actually stall, but rather the -w option is watch option:

 -w, --watch        watch scripts for changes and rerun commands

so run it without this flag: (coffee -o scripts/ -c src/ ) and you will see it exits normally

**Comment by hollybik** [comment]
Usually we don't recommend a local installation - a public implementation is hosted at http://phinch.org (hosted on cloud servers), so usually most people go to the website to load their data onto Phinch. Your data doesn't leave your local machine or get uploaded anywhere, since the visualizations use libraries within Google Chrome to prepare the dataset.
