### ISSUE TITLE
Problem : Phinch recognizing the biom file but not the data

### ISSUE THREAD

**Issue by Anais-Barray** [PitchInteractiveInc/Phinch#62]
Hello Phinch team !

First thank you to help us visualize, compare and magnify our metagenomics data.

I have a major issue :
I am trying to generate biom files with a homemade python script on a unix system, that I know Phinch could accept (when tried with handmade files); the json output seems correct when opened, contains metadata and so on ( : http://codebeautify.org/htmlviewer/cb114a43 ). 

But when I load it into Phinch, the metadata appears, the samples are recognized, but not the data it seems ( : http://imgur.com/a/5LQlo).

When I export data, it is mostly empty ( : http://codebeautify.org/htmlviewer/cb7a542e )

I would be extremely grateful if you had any idea where the formatting could be wrong.

Thank you for your time.
Best regards,
Anaïs.

**Comment by hollybik** [comment]
Hi Anaïs, your BIOM file header says it is formatted as a BIOM v2.1 file (this would be HDF5 format) - however Phinch only accepts BIOM v1.0 files (JSON-formatted). However, your homemade file looks like it is in JSON format, so it might be a problem with the file header - Phinch may not be loading the data because it thinks the file is in BIOM v2.1 format. 

On phinch.org, I would click "load a test file" and then export the file so you can look at the headers and data format. There may be a minor error in your file formatting or header text that is preventing Phinch from loading your file. Make sure all { } [ ] brackets are in the right places and you have the correct punctuation separating everything.

Hope that helps!

**Comment by AdrienSeon** [comment]
Hello,

The "date" metadata of the columns is not ISO8601 compliant which is a problem for Phinch since it analyses automatically any metadata named "date" and is expecting an ISO8601 format to work with.

I didn't see this feature explained anywhere, maybe a warning about this for people not using Phinch with QQIME like Anaïs could be useful.

Hope it helped

**Comment by Anais-Barray** [comment]
Hello again, and thank you both for your answer.

Indeed my files are not BIOM1.0 formatted files, but I have reasons why I cannot, hence I am just converting from hdf5 to JSON with BIOM2.1 version.

The reason why my file couldn't be analyzed properly was indeed because my "Date" metadata was not ISO8601 compliant.

Thanks again !

Best regards,
Anaïs
